package com.CoreService.CoreService.notification.enums;

public enum NotificationType {
    ASSIGNMENT_CREATED,
    ASSIGNMENT_DEADLINE,
    ASSIGNMENT_SUBMITTED,
    ASSIGNMENT_GRADED,
    ATTENDANCE_MARKED,
    CLASSROOM_CREATED,
    CLASSROOM_MEMBER_ADDED,
    CHAT_MESSAGE,
    MATERIAL_UPLOADED,
    MEETING_SCHEDULED,
    MEETING_STARTED,
    SYLLABUS_UPDATED,
    ANNOUNCEMENT
}
